### ISSUE TITLE
Error in plotPhyloCoor when using densiTree on some trees

### ISSUE THREAD

**Issue by richelbilderbeek** [KlausVigo/phangorn#40]
I get the following error, when using densiTree:

```
Error in plotPhyloCoor(tmp, tip.height = tiporder, direction = direction,  : 
  NA/NaN/Inf in foreign function call (arg 4)
```

I must be missing something obvious, that's why I post here: I assume you'd find the error easily. As `plotPhyloCoor` is an internal `ape` function, maybe the problem lies there, and this issue get redirected. 

It depends on the trees if the error occurs. I will give two minimally reproducible examples here, in each I:

 * download a BEAST2 .trees file
 * convert those trees to a multiPhylo
 * plot that multiPhylo

First an example that works just great:

```
devtools::install_github("richelbilderbeek/tracerer")

plottable_trees_filename <- "plottable_anthus_aco.trees"

utils::download.file(
  url = "https://raw.githubusercontent.com/richelbilderbeek/tracerer/develop/inst/extdata/beast2_example_output.trees",
  destfile = plottable_trees_filename,
  method = "wget"
)

trees <- tracerer::parse_beast_trees(plottable_trees_filename)
class(trees) <- "multiPhylo"
testthat::expect_silent(
  phangorn::densiTree(trees)
)
```

Now I wil do exactly the same on a different `.trees` file:

```
devtools::install_github("richelbilderbeek/tracerer")

unplottable_trees_filename <- "unplottable_anthus_aco.trees"

utils::download.file(
  url = "https://raw.githubusercontent.com/richelbilderbeek/tracerer/develop/inst/extdata/unplottable_anthus_aco.trees",
  destfile = unplottable_trees_filename,
  method = "wget"
)

trees <- tracerer::parse_beast_trees(unplottable_trees_filename)
class(trees) <- "multiPhylo"
testthat::expect_silent(
  phangorn::densiTree(trees)
)
```

I have added this problem at [my phangorn fork](https://github.com/richelbilderbeek/phangorn) as a (skipped) test case, so I can submit it as a Pull Request if that would help. I did not do so, as it makes `phangorn` dependent on `tracerer`, which I'd consider a bad idea for the long term.

Note that both .trees files can be plotted by DensiTree ([screenshots](https://github.com/richelbilderbeek/tracerer/issues/4)).

Thanks for your time, Richel Bilderbeek

**Comment by KlausVigo** [comment]
Hi @richelbilderbeek, 
some tiny stupid mistake from my side, should be fixed with commit e4e02f517085cc6b3918215368c35a440c95fb1d . Thanks for the nice reproducible bug report.  
Klaus

**Comment by richelbilderbeek** [comment]
Awesomely done :+1:

**Comment by LunaSare** [comment]
Hi there! 
I realize this is closed, but I'm getting the same error described previously by @richelbilderbeek when plotting trees with densiTree function, with the following example only:

```
devtools::install_github("phylotastic/datelife")
utils::data(birds_and_cats)
biggest_phylo <- get_biggest_phylo(trees = birds_and_cats)
phangorn::densiTree(x = birds_and_cats, consensus = biggest_phylo)
```

Again, the plots are generated, but the error is still coming out.

I am using latest CRAN version of phangorn (2.4.0).

I tried installing the github version to check if the error would come out on that version too, but installation failed
```
devtools::install_github("KlausVigo/phangorn")

ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [phangorn.so] Error 1
ERROR: compilation failed for package ‘phangorn’
* removing ‘/Users/luna/Library/R/3.4/library/phangorn’
* restoring previous ‘/Users/luna/Library/R/3.4/library/phangorn’
Installation failed: Command failed (1)
```

Thanks, 
Luna Sanchez

**Comment by KlausVigo** [comment]
Hi @LunaSare , 
the first issue is that `biggest_phylo` does not contain all species in the trees from `birds_and_cats`
```
> unique(unlist(lapply(birds_and_cats, function(x)x$tip.label)))
 [1] "Gallus gallus"       "Pterocnemia pennata" "Rhea americana"      "Struthio camelus"    "Gallus lafayetii"    "Gallus varius"       "Gallus sonneratii"   "Felis chaus"        
 [9] "Felis margarita"     "Felis nigripes"      "Felis silvestris"    "Felis catus"        
> biggest_phylo$tip.label
 [1] "Gallus lafayetii"    "Gallus sonneratii"   "Gallus gallus"       "Gallus varius"       "Struthio camelus"    "Rhea americana"      "Pterocnemia pennata" "Felis silvestris"   
 [9] "Felis margarita"     "Felis chaus"         "Felis nigripes" 
```
I made a small bugfix to `superTree` (20a7154aafcb8844e9f73c0f10b67f06ffd4d0d0) so that it filters out too small trees to compute a super tree.  
So now 
```
densiTree(birds_and_cats)
```
works with the development version. 

The problem with installing phangorn from github is that xcode nowadays does not contain a FORTRAN compiler any more. You need to install gfortran (see https://gcc.gnu.org/wiki/GFortranBinaries).

Say hello to Brian
Cheers, 
Klaus
